name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Authenticate to GitHub Container Registry (ghcr.io)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests in Dev Container
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          yarn install
          yarn info-rust
          yarn install
          yarn build-raft-server
          yarn test-raft
          yarn test-integration
        imageName: ghcr.io/gianluca-venturini/raft-dev-container